### ISSUE TITLE
Test failures: Connection refused versus Connection reset by peer

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/plone.testing#59]
I see some tests in `plone.testing` and `plone.app.testing` regularly fail on Jenkins, with a Connection refused, or Connection reset by peer. Until now I assumed it was a glitch on Jenkins where a test tries to open a page but the connection is gone. But now I see that the test actually *wants* the connection to fail. The problem is just that it gets a slightly different error.  [Example failure](https://jenkins.plone.org/job/pull-request-5.2/1668/testReport/junit/plone/testing/zope_rst/) on Python 2.7:

```
File "/home/jenkins/.buildout/eggs/cp27m/plone.testing-7.0.0-py2.7.egg/plone/testing/zope.rst", line 526, in zope.rst
Failed example:
    conn = urlopen(app_url + '/folder1', timeout=5)
Expected:
    Traceback (most recent call last):
    ...
    URLError: <urlopen error [Errno ...] Connection refused>
Got:
    Traceback (most recent call last):
      File "/srv/python2.7/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest zope.rst[137]>", line 1, in <module>
        conn = urlopen(app_url + '/folder1', timeout=5)
      File "/srv/python2.7/lib/python2.7/urllib2.py", line 154, in urlopen
        return opener.open(url, data, timeout)
      File "/srv/python2.7/lib/python2.7/urllib2.py", line 429, in open
        response = self._open(req, data)
      File "/srv/python2.7/lib/python2.7/urllib2.py", line 447, in _open
        '_open', req)
      File "/srv/python2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
        result = func(*args)
      File "/srv/python2.7/lib/python2.7/urllib2.py", line 1228, in http_open
        return self.do_open(httplib.HTTPConnection, req)
      File "/srv/python2.7/lib/python2.7/urllib2.py", line 1201, in do_open
        r = h.getresponse(buffering=True)
      File "/srv/python2.7/lib/python2.7/httplib.py", line 1121, in getresponse
        response.begin()
      File "/srv/python2.7/lib/python2.7/httplib.py", line 438, in begin
        version, status, reason = self._read_status()
      File "/srv/python2.7/lib/python2.7/httplib.py", line 394, in _read_status
        line = self.fp.readline(_MAXLINE + 1)
      File "/srv/python2.7/lib/python2.7/socket.py", line 480, in readline
        data = self._sock.recv(self._rbufsize)
    error: [Errno 104] Connection reset by peer
```

Similar one for [`plone.app.testing`](https://jenkins.plone.org/job/plone-5.2-python-3.7/182/testReport/junit/plone.app/testing/layers_rst/) on Python 3.7 instead of 2.7:

```
File "/home/jenkins/.buildout/eggs/cp37m/plone.app.testing-6.1.1-py3.7.egg/plone/app/testing/layers.rst", line 377, in layers.rst
Failed example:
    conn = urlopen(portal_url + '/folder1', timeout=5) # doctest: +IGNORE_EXCEPTION_DETAIL
Expected:
    Traceback (most recent call last):
    ...
    urllib.error.URLError: <urlopen error [Errno 61] Connection refused>
Got:
    Traceback (most recent call last):
      File "/srv/python3.7/lib/python3.7/doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest layers.rst[105]>", line 1, in <module>
        conn = urlopen(portal_url + '/folder1', timeout=5) # doctest: +IGNORE_EXCEPTION_DETAIL
      File "/srv/python3.7/lib/python3.7/urllib/request.py", line 222, in urlopen
        return opener.open(url, data, timeout)
      File "/srv/python3.7/lib/python3.7/urllib/request.py", line 525, in open
        response = self._open(req, data)
      File "/srv/python3.7/lib/python3.7/urllib/request.py", line 543, in _open
        '_open', req)
      File "/srv/python3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
        result = func(*args)
      File "/srv/python3.7/lib/python3.7/urllib/request.py", line 1345, in http_open
        return self.do_open(http.client.HTTPConnection, req)
      File "/srv/python3.7/lib/python3.7/urllib/request.py", line 1320, in do_open
        r = h.getresponse()
      File "/srv/python3.7/lib/python3.7/http/client.py", line 1321, in getresponse
        response.begin()
      File "/srv/python3.7/lib/python3.7/http/client.py", line 296, in begin
        version, status, reason = self._read_status()
      File "/srv/python3.7/lib/python3.7/http/client.py", line 257, in _read_status
        line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
      File "/srv/python3.7/lib/python3.7/socket.py", line 589, in readinto
        return self._sock.recv_into(b)
    ConnectionResetError: [Errno 104] Connection reset by peer
```

That one has `IGNORE_EXCEPTION_DETAIL` but that is apparently not working the way we want.
Possible pointer on [stackoverflow](https://stackoverflow.com/questions/17671147/how-to-test-exceptions-with-doctest-in-python-2-x-and-3-x).

**Comment by mauritsvanrees** [comment]
This is currently a problem again on Jenkins. Various Plone 5.2 jobs are broken with this failure, for example [this one](https://jenkins.plone.org/job/plone-5.2-python-3.6/568/testReport/plone/testing/zope_rst/).
I restarted several jobs, but the problem persists.

**Comment by mauritsvanrees** [comment]
Related PR is merged.
There may be similar problems, but we can handle them when they surface.
Closing.
